/**
 * Cross-implementation conformance: the TypeScript reference must keep producing
 * the committed corpus, and the Rust crate asserts against the same files
 * (`crates/wh40kdc/tests/conformance.rs`). The corpus is generated by
 * `npm run gen:conformance`; a CI drift guard keeps it current. This is where
 * the two toolchains tie out.
 */
import { describe, it, expect } from "vitest";
import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { Dataset } from "../src/data/dataset.js";
import { normalizeName } from "../src/data/normalize.js";
import { importRoster } from "../src/import/import-listforge.js";

const CONFORMANCE = join(dirname(fileURLToPath(import.meta.url)), "../../conformance");
const readJson = (path: string): unknown => JSON.parse(readFileSync(path, "utf8"));

describe("conformance corpus (ties out with the Rust crate)", () => {
  it("normalizeName matches every case in normalize.json", () => {
    const table = readJson(join(CONFORMANCE, "normalize.json")) as {
      input: string;
      expected: string;
    }[];
    expect(table.length).toBeGreaterThan(0);
    for (const { input, expected } of table) {
      expect(normalizeName(input), `normalizeName(${JSON.stringify(input)})`).toBe(expected);
    }
  });

  it("importRoster reproduces every roster golden", () => {
    const ds = Dataset.embedded();
    const rosterDir = join(CONFORMANCE, "roster");
    const cases = readdirSync(rosterDir, { withFileTypes: true }).filter((e) => e.isDirectory());
    expect(cases.length).toBeGreaterThan(0);

    for (const entry of cases) {
      const caseDir = join(rosterDir, entry.name);
      const input = readJson(join(caseDir, "input.json"));
      const expected = readJson(join(caseDir, "expected.roster.json"));
      const actual = importRoster(input, { dataset: ds });
      // Round-trip through JSON so the comparison is structural (key order and
      // class instances don't matter), matching the Rust serde_json equality.
      expect(JSON.parse(JSON.stringify(actual)), `roster/${entry.name}`).toEqual(expected);
    }
  });
});
