//! Cross-implementation conformance: the Rust crate must reproduce the
//! reference (TypeScript) outputs byte-for-byte (structurally).
//!
//! Both implementations assert against one committed corpus under repo-root
//! `conformance/`, generated by the TS reference (`npm run gen:conformance`).
//! The TS suite (`tools/test/conformance.test.ts`) asserts the same files, and a
//! CI drift guard keeps the goldens current — so a lookup or import that
//! resolves in TS resolves identically here. This is where the two toolchains
//! tie out.

#![cfg(feature = "import")]

use std::path::PathBuf;

use serde_json::Value;
use wh40kdc::import::import_roster;
use wh40kdc::{normalize_name, Dataset};

fn conformance_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../conformance")
}

fn read_json(path: &PathBuf) -> Value {
    let raw =
        std::fs::read_to_string(path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
    serde_json::from_str(&raw).expect("corpus file is valid JSON")
}

#[test]
fn normalize_name_matches_reference_corpus() {
    let table = read_json(&conformance_dir().join("normalize.json"));
    let cases = table.as_array().expect("normalize.json is an array");
    assert!(!cases.is_empty(), "normalize corpus is empty");

    for case in cases {
        let input = case["input"].as_str().expect("case.input is a string");
        let expected = case["expected"]
            .as_str()
            .expect("case.expected is a string");
        assert_eq!(
            normalize_name(input),
            expected,
            "normalize_name({input:?}) diverged from the TS reference"
        );
    }
}

#[test]
fn imported_rosters_match_reference_goldens() {
    let ds = Dataset::embedded();
    let roster_dir = conformance_dir().join("roster");
    let mut cases = 0;

    for entry in std::fs::read_dir(&roster_dir).expect("roster corpus dir is readable") {
        let case_dir = entry.expect("dir entry").path();
        if !case_dir.is_dir() {
            continue;
        }
        let input = read_json(&case_dir.join("input.json"));
        let expected = read_json(&case_dir.join("expected.roster.json"));

        let roster = import_roster(&input, ds)
            .unwrap_or_else(|e| panic!("import {}: {e}", case_dir.display()));
        let actual = serde_json::to_value(&roster).expect("roster serializes");

        assert_eq!(
            actual,
            expected,
            "roster case {:?} diverged from the TS golden",
            case_dir.file_name().unwrap()
        );
        cases += 1;
    }

    assert!(cases > 0, "no roster conformance cases found");
}
