/**
 * Audit dangling unit references: unit_ids named by enrichment data that no
 * core `units.json` (in any faction) defines.
 *
 * Enrichment was seeded ahead of core for the 11th-edition pre-launch
 * provisional dataslate — ability stubs reference datasheets that were never
 * ingested into `data/core/<faction>/units.json`. This script enumerates those
 * holes so they can be filled (e.g. via `import-catalog.ts`).
 *
 * The "missing" test mirrors `link-abilities.ts`: a unit_id is only dangling
 * when NO core file claims it, because enrichment for a sub-faction (e.g. Blood
 * Angels) legitimately references units defined in a parent core file
 * (adeptus-astartes). The diff is therefore against a single global set of all
 * core unit ids.
 *
 * Writes `data/_audit/missing-units.json` and `data/_audit/missing-units.md`,
 * grouped by the enrichment faction that references the unit.
 *
 * Usage:
 *   npx tsx tools/src/audit-missing-units.ts            # write reports
 *   npx tsx tools/src/audit-missing-units.ts --dry-run  # print summary only
 */

import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DEFAULT_ROOT = resolve(__dirname, "../..");

interface EnrichmentAbility {
  ability_id: string | null;
  unit_ids: string[] | null;
  game_version?: { edition?: string; dataslate?: string } | null;
}

interface CoreUnit {
  id: string;
}

export interface MissingUnit {
  faction: string;
  unit_id: string;
  referenced_by: string[];
}

export interface MissingUnitsReport {
  generatedFrom: string;
  totalMissing: number;
  byFaction: Record<string, MissingUnit[]>;
}

export interface AuditOptions {
  rootDir?: string;
  dryRun?: boolean;
}

function readJSON<T>(path: string): T {
  return JSON.parse(readFileSync(path, "utf-8")) as T;
}

function listFactionDirs(dir: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !e.name.startsWith("_"))
    .map((e) => e.name)
    .sort();
}

export function auditMissingUnits(opts: AuditOptions = {}): MissingUnitsReport {
  const root = opts.rootDir ?? DEFAULT_ROOT;
  const coreDir = resolve(root, "data/core");
  const enrichmentDir = resolve(root, "data/enrichment");

  // Global set of every defined core unit id, across all factions.
  const coreUnitIds = new Set<string>();
  for (const faction of listFactionDirs(coreDir)) {
    const path = join(coreDir, faction, "units.json");
    if (!existsSync(path)) continue;
    for (const u of readJSON<CoreUnit[]>(path)) coreUnitIds.add(u.id);
  }

  // For each enrichment faction, collect referenced unit_ids → referencing abilities.
  const byFaction: Record<string, MissingUnit[]> = {};
  let totalMissing = 0;

  for (const faction of listFactionDirs(enrichmentDir)) {
    const path = join(enrichmentDir, faction, "abilities.json");
    if (!existsSync(path)) continue;

    const refs = new Map<string, Set<string>>(); // unit_id → ability_ids
    for (const a of readJSON<EnrichmentAbility[]>(path)) {
      if (!a.unit_ids) continue;
      for (const unitId of a.unit_ids) {
        if (coreUnitIds.has(unitId)) continue; // defined somewhere → not a hole
        let set = refs.get(unitId);
        if (!set) refs.set(unitId, (set = new Set()));
        if (a.ability_id) set.add(a.ability_id);
      }
    }

    if (refs.size === 0) continue;
    const missing: MissingUnit[] = [...refs.entries()]
      .map(([unit_id, abilitySet]) => ({
        faction,
        unit_id,
        referenced_by: [...abilitySet].sort(),
      }))
      .sort((a, b) => a.unit_id.localeCompare(b.unit_id));
    byFaction[faction] = missing;
    totalMissing += missing.length;
  }

  return {
    generatedFrom: "tools/src/audit-missing-units.ts",
    totalMissing,
    byFaction,
  };
}

function renderMarkdown(report: MissingUnitsReport): string {
  const factions = Object.keys(report.byFaction).sort();
  const lines: string[] = [];
  lines.push("# Missing-unit audit");
  lines.push("");
  lines.push(
    "Generated by `tools/src/audit-missing-units.ts` (`npm run audit:missing-units`).",
  );
  lines.push(
    "Lists unit_ids referenced by enrichment abilities that no core `units.json` defines —",
  );
  lines.push(
    "the datasheet \"holes\" left when enrichment was seeded ahead of core. Fill via",
  );
  lines.push("`tools/src/import-catalog.ts` against the BattleScribe `.cat` source.");
  lines.push("");
  lines.push(`**Total missing: ${report.totalMissing}**`);
  lines.push("");
  lines.push("| faction | missing |");
  lines.push("|---|--:|");
  for (const f of factions) {
    lines.push(`| ${f} | ${report.byFaction[f].length} |`);
  }
  lines.push("");
  for (const f of factions) {
    lines.push(`## ${f} (${report.byFaction[f].length})`);
    lines.push("");
    for (const m of report.byFaction[f]) {
      lines.push(
        `- \`${m.unit_id}\` — referenced by: ${m.referenced_by
          .map((a) => `\`${a}\``)
          .join(", ")}`,
      );
    }
    lines.push("");
  }
  return lines.join("\n") + "\n";
}

// ─── CLI ────────────────────────────────────────────────────────────────

const isMain =
  process.argv[1] &&
  resolve(process.argv[1]).replace(/\.\w+$/, "") ===
    fileURLToPath(import.meta.url).replace(/\.\w+$/, "");

if (isMain) {
  const args = process.argv.slice(2);
  if (args.includes("--help") || args.includes("-h")) {
    console.log(
      "Usage: npx tsx tools/src/audit-missing-units.ts [--dry-run]",
    );
    process.exit(0);
  }

  const dryRun = args.includes("--dry-run");
  const report = auditMissingUnits();
  const auditDir = resolve(DEFAULT_ROOT, "data/_audit");

  console.log(`Total missing units: ${report.totalMissing}`);
  for (const f of Object.keys(report.byFaction).sort()) {
    console.log(`  ${f}: ${report.byFaction[f].length}`);
  }

  if (!dryRun) {
    writeFileSync(
      join(auditDir, "missing-units.json"),
      JSON.stringify(report, null, 2) + "\n",
    );
    writeFileSync(join(auditDir, "missing-units.md"), renderMarkdown(report));
    console.log(
      `\nWrote data/_audit/missing-units.json and data/_audit/missing-units.md`,
    );
  } else {
    console.log("\n(dry-run; no files written)");
  }
}
