/**
 * audit:store-coverage — report per-faction coverage of the out-of-repo
 * `40kdc-abilities` raw-text store vs the enrichment ability set, into
 * `data/_audit/store-coverage.md`. Counts only — never reads/emits rules text,
 * so it is safe to run and commit in this (public) repo.
 *
 * Usage: npx tsx tools/src/audit-store-coverage.ts [--store <dir>]
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const REPO = resolve(__dirname, "../..");
const ENRICH = resolve(REPO, "data/enrichment");
const args = process.argv.slice(2);
const storeArg = args.indexOf("--store");
const STORE_ROOT = resolve(REPO, storeArg >= 0 ? args[storeArg + 1] : "../40kdc-abilities");

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const readJSON = (p: string): any => JSON.parse(readFileSync(p, "utf-8"));

const CORE = resolve(REPO, "data/core");
// the app resolves text for each of these via store[ability_id ?? id]
const keyOf = (e: { ability_id?: string; id?: string }): string => e.ability_id ?? e.id ?? "";
const allDirs = [...new Set([...readdirSync(ENRICH), ...readdirSync(CORE)])].filter((f) => !f.startsWith("_")).sort();

interface Row { faction: string; enr: [number, number]; enh: [number, number]; strat: [number, number] }
const rows: Row[] = [];
const tot = { enr: [0, 0], enh: [0, 0], strat: [0, 0] } as Record<string, [number, number]>;

for (const f of allDirs) {
  const sp = join(STORE_ROOT, `${f}.json`);
  const have = new Set((existsSync(sp) ? readJSON(sp) : []).map((e: { ability_id: string }) => e.ability_id));
  const cov = (items: { ability_id?: string; id?: string }[]): [number, number] => [items.length, items.filter((e) => have.has(keyOf(e))).length];
  const load = (p: string) => (existsSync(p) ? readJSON(p) : []);
  const enr = cov(load(join(ENRICH, f, "abilities.json")).map((e: { ability_id: string }) => ({ ability_id: e.ability_id })));
  const enh = cov(load(join(CORE, f, "enhancements.json")));
  const strat = cov(load(join(CORE, f, "stratagems.json")));
  if (enr[0] + enh[0] + strat[0] === 0) continue;
  rows.push({ faction: f, enr, enh, strat });
  for (const [k, v] of [["enr", enr], ["enh", enh], ["strat", strat]] as const) { tot[k][0] += v[0]; tot[k][1] += v[1]; }
}
rows.sort((a, b) => (b.enr[0] - b.enr[1] + b.enh[0] - b.enh[1] + b.strat[0] - b.strat[1]) - (a.enr[0] - a.enr[1] + a.enh[0] - a.enh[1] + a.strat[0] - a.strat[1]));

const cell = ([t, c]: [number, number]): string => (t === 0 ? "—" : `${c}/${t}`);
let md = "# Raw-text store coverage\n\n";
md += "Coverage of the out-of-repo `40kdc-abilities` raw-text store, by the lookup the app uses: `store[ability_id ?? id]` ";
md += "for enrichment abilities (unit datasheet/army rules), core enhancements, and core stratagems. ";
md += "Generated by `npm run audit:store-coverage` — counts only, no rules text (which never enters this repo).\n\n";
md += "Backfilled from game-datacards 10e via `npm run author:backfill-store` (fill-only — never overwrites 11e prose from `author:ingest`). ";
md += "Residual gaps: universal USR keywords (no verbatim source) and new 11e faction-pack content absent from the 10e datasources.\n\n";
md += "| faction | enrichment | enhancements | stratagems |\n|---|--:|--:|--:|\n";
for (const r of rows) md += `| ${r.faction} | ${cell(r.enr)} | ${cell(r.enh)} | ${cell(r.strat)} |\n`;
md += `| **TOTAL** | **${tot.enr[1]}/${tot.enr[0]}** | **${tot.enh[1]}/${tot.enh[0]}** | **${tot.strat[1]}/${tot.strat[0]}** |\n`;

writeFileSync(resolve(REPO, "data/_audit/store-coverage.md"), md);
const pct = (b: [number, number]) => Math.round((b[1] / b[0]) * 100);
console.log(`store-coverage → data/_audit/store-coverage.md  | enrichment ${pct(tot.enr)}%  enhancements ${pct(tot.enh)}%  stratagems ${pct(tot.strat)}%`);
