/**
 * audit:store-coverage — report per-faction coverage of the out-of-repo
 * `40kdc-abilities` raw-text store vs the enrichment ability set, into
 * `data/_audit/store-coverage.md`. Counts only — never reads/emits rules text,
 * so it is safe to run and commit in this (public) repo.
 *
 * Usage: npx tsx tools/src/audit-store-coverage.ts [--store <dir>]
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const REPO = resolve(__dirname, "../..");
const ENRICH = resolve(REPO, "data/enrichment");
const args = process.argv.slice(2);
const storeArg = args.indexOf("--store");
const STORE_ROOT = resolve(REPO, storeArg >= 0 ? args[storeArg + 1] : "../40kdc-abilities");

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const readJSON = (p: string): any => JSON.parse(readFileSync(p, "utf-8"));

const rows: [string, number, number, number][] = [];
let tEnr = 0, tHave = 0;
for (const f of readdirSync(ENRICH)) {
  const ap = join(ENRICH, f, "abilities.json");
  if (!existsSync(ap)) continue;
  const enr = readJSON(ap);
  const sp = join(STORE_ROOT, `${f}.json`);
  const store = existsSync(sp) ? readJSON(sp) : [];
  const have = new Set(store.map((e: { ability_id: string }) => e.ability_id));
  const cov = enr.filter((e: { ability_id: string }) => have.has(e.ability_id)).length;
  rows.push([f, enr.length, cov, enr.length - cov]);
  tEnr += enr.length; tHave += cov;
}
rows.sort((a, b) => b[3] - a[3]);

let md = "# Raw-text store coverage\n\n";
md += "Per-faction coverage of the out-of-repo `40kdc-abilities` raw-text store vs the enrichment ability set. ";
md += "Generated by `npm run audit:store-coverage`. The store holds verbatim rules text keyed by `ability_id` ";
md += "(never committed to this repo); this table tracks only counts.\n\n";
md += "Backfilled from game-datacards 10e via `npm run author:backfill-store` (fill-only). Residual gaps are ";
md += "universal USR keywords (no verbatim source) and new 11e faction-pack content absent from the 10e datasources.\n\n";
md += "| faction | abilities | in store | missing |\n|---|--:|--:|--:|\n";
for (const r of rows) md += `| ${r[0]} | ${r[1]} | ${r[2]} | ${r[3]} |\n`;
md += `| **TOTAL** | **${tEnr}** | **${tHave}** | **${tEnr - tHave}** |\n`;

writeFileSync(resolve(REPO, "data/_audit/store-coverage.md"), md);
console.log(`store-coverage: ${tHave}/${tEnr} (${Math.round((tHave / tEnr) * 100)}%) covered, ${tEnr - tHave} missing → data/_audit/store-coverage.md`);
