//! Repo automation. Currently one task: `codegen`, which regenerates
//! `crates/wh40kdc/src/generated.rs` from the bundled JSON Schema.
//!
//! Run with `cargo run -p xtask -- codegen`. The bundled schema itself is
//! produced upstream by `cd tools && npm run bundle:schemas`.

use std::path::PathBuf;

use anyhow::{bail, Context, Result};
use schemars::schema::RootSchema;
use typify::{TypeSpace, TypeSpaceSettings};

fn main() -> Result<()> {
    match std::env::args().nth(1).as_deref() {
        Some("codegen") => codegen(),
        other => bail!(
            "unknown task {:?}; expected `codegen`",
            other.unwrap_or("<none>")
        ),
    }
}

/// Workspace root = parent of the xtask crate dir.
fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask has a parent dir")
        .to_path_buf()
}

fn codegen() -> Result<()> {
    let root = workspace_root();
    let schema_path = root.join("crates/wh40kdc/schemas/bundled.schema.json");
    let out_path = root.join("crates/wh40kdc/src/generated.rs");

    let content = std::fs::read_to_string(&schema_path)
        .with_context(|| format!("reading {}", schema_path.display()))?;
    let schema: RootSchema = serde_json::from_str(&content)
        .with_context(|| format!("parsing {} as a JSON Schema", schema_path.display()))?;

    let mut settings = TypeSpaceSettings::default();
    // typify already derives Serialize, Deserialize, Debug, Clone; add PartialEq
    // so generated types are comparable (used by the round-trip integration test).
    settings.with_derive("PartialEq".to_string());

    let mut type_space = TypeSpace::new(&settings);
    type_space
        .add_root_schema(schema)
        .context("typify failed to ingest the bundled schema")?;

    let tokens = type_space.to_stream();
    let file = syn::parse2::<syn::File>(tokens)
        .context("generated token stream did not parse as a Rust file")?;
    let formatted = prettyplease::unparse(&file);

    // The `mod generated` declaration in lib.rs carries `#[rustfmt::skip]`, so
    // `cargo fmt` leaves prettyplease's output alone (avoids a conflict with the
    // CI drift check).
    let header = "// @generated by `cargo run -p xtask -- codegen` — do not edit by hand.\n\
                  // Source of truth: crates/wh40kdc/schemas/bundled.schema.json\n\
                  // (regenerate that first via `cd tools && npm run bundle:schemas`).\n\n";

    std::fs::write(&out_path, format!("{header}{formatted}"))
        .with_context(|| format!("writing {}", out_path.display()))?;

    println!("Wrote {}", out_path.display());
    Ok(())
}
